# Basic Site Settings
locale                   : "en-US"
site_theme               : "Academic Portfolio"
title_separator          : "-"
name                     : &name ishita iqbal oishee
description              : &description "Academic portfolio of Shahrukh Mithun"
url                      : https://YOUR-USERNAME.github.io  
baseurl                  : ""
repository               : "YOUR-USERNAME/YOUR-REPO-NAME"

# Author Info
author:
  avatar           : "profile.png"
  name             : "Shahrukh Mithun"
  pronouns         :  
  bio              : "Graduate in History and Civilisation | Researcher"
  location         : "Barishal, Bangladesh"
  employer         : "NGO Sector (Child Awareness Project)"
  uri              : 
  email            : "your-email@gmail.com" 

  # Academic links
  googlescholar    : 
  orcid            : 
  pubmed           : 

  # Coding
  github           : "YOUR-GITHUB-USERNAME"

  # Social
  linkedin         : 
  facebook         : 
  twitter          : 

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Markdown
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
